In [1]:
import os
import deepdrr
from deepdrr import geo
from deepdrr.utils import test_utils, image_utils
from deepdrr.projector import Projector
from pathlib import Path
import itertools

import numpy as np
import pandas as pd
import meshlib.mrmeshpy as mr
import meshlib.mrmeshnumpy as mrn
import random

base_path = "/mnt/c/Users/caspe/Thesis-Synthex/"
data_path = "data/RAD-ChestCT-NIFTI/"
output_path = "/home/casper/radchest_3dmodel/"
import matplotlib.pyplot as plt


In [6]:
angles = [j for j in itertools.product([i for i in range(-10, 15, 5)], [i for i in range(-10, 15, 5)]) if not ((5 in j and 0 in j) or (-5 in j and 0 in j))]


In [8]:
len(angles)

21

In [92]:
input_path= "/mnt/c/Users/caspe/Thesis-Synthex/data/RAD-ChestCT-NIFTI/trn00139.nii.gz"

carm = deepdrr.MobileCArm(
    sensor_height=2500, 
    sensor_width=2500,
    source_to_detector_distance=2000,
    source_to_isocenter_vertical_distance=2000,
    pixel_size=0.18
)

patient = deepdrr.Volume.from_nifti(
    Path(input_path), 
    use_thresholding=False,
)


Using downloaded and verified file: /home/casper/datasets/DeepDRR_DATA/model_segmentation.pth.tar


In [93]:
air = patient.materials["air"]
soft_tissue = patient.materials["soft tissue"]
bone = patient.materials["bone"]

In [94]:
patient.materials["air"]=np.zeros(patient.materials["air"].shape, dtype=np.float32)
patient.materials["soft tissue"]=np.zeros(patient.materials["soft tissue"].shape, dtype=np.float32)
patient.materials["bone"]=np.zeros(patient.materials["bone"].shape, dtype=np.float32)

patient.materials["bone"] = bone

for angle in angles:

    carm = deepdrr.MobileCArm(
        sensor_height=2500, 
        sensor_width=2500,
        source_to_detector_distance=2000,
        source_to_isocenter_vertical_distance=2000,
        pixel_size=0.18
    )


    with Projector(patient, carm=carm) as projector:
        patient.orient_patient(head_first=True, supine=True)
        patient.place_center(carm.isocenter_in_world)

        carm.move_by(
            delta_alpha=angle[0],
            delta_beta=angle[1],
        )

        image = projector()

    path = Path(output_path + f"bone_{angle[0]}_{angle[1]}.png")
    image_utils.save(path, image)

    print(f"saved example projection image to {path.absolute()}")



saved example projection image to /home/casper/radchest_3dmodel/bone_-10_-10.png
saved example projection image to /home/casper/radchest_3dmodel/bone_-10_-5.png
saved example projection image to /home/casper/radchest_3dmodel/bone_-10_0.png
saved example projection image to /home/casper/radchest_3dmodel/bone_-10_5.png
saved example projection image to /home/casper/radchest_3dmodel/bone_-10_10.png
saved example projection image to /home/casper/radchest_3dmodel/bone_-5_-10.png
saved example projection image to /home/casper/radchest_3dmodel/bone_-5_-5.png
saved example projection image to /home/casper/radchest_3dmodel/bone_-5_5.png
saved example projection image to /home/casper/radchest_3dmodel/bone_-5_10.png
saved example projection image to /home/casper/radchest_3dmodel/bone_0_-10.png
saved example projection image to /home/casper/radchest_3dmodel/bone_0_0.png
saved example projection image to /home/casper/radchest_3dmodel/bone_0_10.png
saved example projection image to /home/casper/radc

In [95]:
patient.materials["air"]=np.zeros(patient.materials["air"].shape, dtype=np.float32)
patient.materials["soft tissue"]=np.zeros(patient.materials["soft tissue"].shape, dtype=np.float32)
patient.materials["bone"]=np.zeros(patient.materials["bone"].shape, dtype=np.float32)

patient.materials["soft tissue"] = soft_tissue

for angle in angles:

    carm = deepdrr.MobileCArm(
        sensor_height=2500, 
        sensor_width=2500,
        source_to_detector_distance=2000,
        source_to_isocenter_vertical_distance=2000,
        pixel_size=0.18
    )


    with Projector(patient, carm=carm) as projector:
        patient.orient_patient(head_first=True, supine=True)
        patient.place_center(carm.isocenter_in_world)

        carm.move_by(
            delta_alpha=angle[0],
            delta_beta=angle[1],
        )

        image = projector()

    path = Path(output_path + f"soft_tissue_{angle[0]}_{angle[1]}.png")
    image_utils.save(path, image)

    print(f"saved example projection image to {path.absolute()}")


saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_-10_-10.png
saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_-10_-5.png
saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_-10_0.png
saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_-10_5.png
saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_-10_10.png
saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_-5_-10.png
saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_-5_-5.png
saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_-5_5.png
saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_-5_10.png
saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_0_-10.png
saved example projection image to /home/casper/radchest_3dmodel/soft_tissue_0_0.png
saved example projection image to /home/casper/radch

In [96]:
patient.materials["air"]=np.zeros(patient.materials["air"].shape, dtype=np.float32)
patient.materials["soft tissue"]=np.zeros(patient.materials["soft tissue"].shape, dtype=np.float32)
patient.materials["bone"]=np.zeros(patient.materials["bone"].shape, dtype=np.float32)

patient.materials["air"] = air

for angle in angles:

    carm = deepdrr.MobileCArm(
        sensor_height=2500, 
        sensor_width=2500,
        source_to_detector_distance=2000,
        source_to_isocenter_vertical_distance=2000,
        pixel_size=0.18
    )


    with Projector(patient, carm=carm) as projector:
        patient.orient_patient(head_first=True, supine=True)
        patient.place_center(carm.isocenter_in_world)

        carm.move_by(
            delta_alpha=angle[0],
            delta_beta=angle[1],
        )

        image = projector()

    path = Path(output_path + f"air_{angle[0]}_{angle[1]}.png")
    image_utils.save(path, image)

    print(f"saved example projection image to {path.absolute()}")


saved example projection image to /home/casper/radchest_3dmodel/air_-10_-10.png
saved example projection image to /home/casper/radchest_3dmodel/air_-10_-5.png
saved example projection image to /home/casper/radchest_3dmodel/air_-10_0.png
saved example projection image to /home/casper/radchest_3dmodel/air_-10_5.png
saved example projection image to /home/casper/radchest_3dmodel/air_-10_10.png
saved example projection image to /home/casper/radchest_3dmodel/air_-5_-10.png
saved example projection image to /home/casper/radchest_3dmodel/air_-5_-5.png
saved example projection image to /home/casper/radchest_3dmodel/air_-5_5.png
saved example projection image to /home/casper/radchest_3dmodel/air_-5_10.png
saved example projection image to /home/casper/radchest_3dmodel/air_0_-10.png
saved example projection image to /home/casper/radchest_3dmodel/air_0_0.png
saved example projection image to /home/casper/radchest_3dmodel/air_0_10.png
saved example projection image to /home/casper/radchest_3dmodel

In [99]:
def create_circular_mask(h, w, center=None, radius=None):

    if center is None: # use the middle of the image
        center = (int(w/2), int(h/2))
    if radius is None: # use the smallest distance between the center and image walls
        radius = min(center[0], center[1], w-center[0], h-center[1])

    Y, X = np.ogrid[:h, :w]
    dist_from_center = np.sqrt((X - center[0])**2 + (Y-center[1])**2)

    mask = dist_from_center <= radius
    return mask

In [102]:
circle_mask = create_circular_mask(air.shape[1],air.shape[2], radius=185)

circle_mask = ~circle_mask

air_ = air.copy()
bone_ = bone.copy()
soft_tissue_ = soft_tissue.copy()

for i in range(air.shape[0]):
    air_[i] = air_[i] - circle_mask
    bone_[i] = bone_[i] - circle_mask
    soft_tissue_[i] = soft_tissue_[i] - circle_mask

In [103]:

#convert 3D array to SimpleVolume data
simpleVolume = mrn.simpleVolumeFrom3Darray(air_)

#convert SimpleVolume to FloatGrid data
floatGrid = mr.simpleVolumeToDenseGrid(simpleVolume )

#make mesh by iso-value = 0.5 and voxel size = (0.1, 0.1, 0.1)
mesh = mr.gridToMesh(floatGrid , mr.Vector3f(0.1, 0.1, 0.1), 0.5)

#save mesh
mr.saveMesh(mesh, Path("/mnt/c/Users/caspe/Desktop/air_.stl") )

In [104]:
import meshlib.mrmeshpy as mr
import meshlib.mrmeshnumpy as mrn
#convert 3D array to SimpleVolume data
simpleVolume = mrn.simpleVolumeFrom3Darray(bone_)

#convert SimpleVolume to FloatGrid data
floatGrid = mr.simpleVolumeToDenseGrid(simpleVolume )

#make mesh by iso-value = 0.5 and voxel size = (0.1, 0.1, 0.1)
mesh = mr.gridToMesh(floatGrid , mr.Vector3f(0.1, 0.1, 0.1), 0.5)

#save mesh
mr.saveMesh(mesh, Path("/mnt/c/Users/caspe/Desktop/bone_.stl") )

In [105]:
import meshlib.mrmeshpy as mr
import meshlib.mrmeshnumpy as mrn
#convert 3D array to SimpleVolume data
simpleVolume = mrn.simpleVolumeFrom3Darray(soft_tissue_)

#convert SimpleVolume to FloatGrid data
floatGrid = mr.simpleVolumeToDenseGrid(simpleVolume )

#make mesh by iso-value = 0.5 and voxel size = (0.1, 0.1, 0.1)
mesh = mr.gridToMesh(floatGrid , mr.Vector3f(0.1, 0.1, 0.1), 0.5)

#save mesh
mr.saveMesh(mesh, Path("/mnt/c/Users/caspe/Desktop/soft_tissue_.stl") )

In [15]:
volumes = os.listdir(base_path + data_path)

random.shuffle(angles)

for idx, volume in enumerate(volumes):
    if not volume.endswith(".nii.gz"):
        continue

    patient = deepdrr.Volume.from_nifti(
        Path(base_path + data_path + volume), 
        use_thresholding=False,
    )
    random.shuffle(angles)
    for angle in angles[:9]:

        carm = deepdrr.MobileCArm(
            sensor_height=2500, 
            sensor_width=2500,
            source_to_detector_distance=2000,
            source_to_isocenter_vertical_distance=2000,
            pixel_size=0.18
        )


        with Projector(patient, carm=carm) as projector:
            patient.orient_patient(head_first=True, supine=True)
            patient.place_center(carm.isocenter_in_world)

            carm.move_by(
                delta_alpha=angle[0],
                delta_beta=angle[1],
            )

            image = projector()

        path = Path(output_path + f"{volume}_{angle[0]}_{angle[1]}.png")
        image_utils.save(path, image)

        print(f"saved example projection image to {path.absolute()}")


Using downloaded and verified file: /home/casper/datasets/DeepDRR_DATA/model_segmentation.pth.tar
saved example projection image to /home/casper/RADCHEST/trn00067.nii.gz_-5_-10.png
saved example projection image to /home/casper/RADCHEST/trn00067.nii.gz_10_-10.png
saved example projection image to /home/casper/RADCHEST/trn00067.nii.gz_5_-5.png
saved example projection image to /home/casper/RADCHEST/trn00067.nii.gz_10_10.png
saved example projection image to /home/casper/RADCHEST/trn00067.nii.gz_-10_10.png
saved example projection image to /home/casper/RADCHEST/trn00067.nii.gz_-10_0.png
saved example projection image to /home/casper/RADCHEST/trn00067.nii.gz_-10_-10.png
saved example projection image to /home/casper/RADCHEST/trn00067.nii.gz_0_-10.png
saved example projection image to /home/casper/RADCHEST/trn00067.nii.gz_10_0.png
Using downloaded and verified file: /home/casper/datasets/DeepDRR_DATA/model_segmentation.pth.tar
saved example projection image to /home/casper/RADCHEST/trn0009

In [58]:
carm.arm_from_device

FrameTransform(  [[ 1.  0.  0. -0.]
   [ 0.  1.  0. -0.]
   [ 0.  0.  1. -0.]
   [ 0.  0.  0.  1.]])

In [71]:
image_utils.save("ddr.png", image)

PosixPath('ddr.png')

In [70]:
patient.materials["bone"].shape

(401, 450, 450)

In [59]:
carm.source_to_detector_distance

2000

In [69]:
2000/0.2

10000.0

In [68]:
carm.camera_intrinsics

CameraIntrinsicTransform(  [[10000.     0.  1250.]
   [    0. 10000.  1250.]
   [    0.     0.     1.]])

In [62]:
2000*0.175

350.0

In [6]:
carm.get_camera_projection()

CameraProjection(  [[  -3906.8267   -3278.217     1250.     1287500.    ]
   [   3278.217    -3906.8267    1250.     1287500.    ]
   [      0.           0.           1.        1030.    ]])